// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsKxAZNnD7ASV0EYcek3ZsGbdsf2mgf-c',
    appId: '1:854249361826:web:31fff6ced2e7aa62d022fb',
    messagingSenderId: '854249361826',
    projectId: 'evently-route',
    authDomain: 'evently-route.firebaseapp.com',
    storageBucket: 'evently-route.firebasestorage.app',
    measurementId: 'G-96QQLG1BP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsXrYialHhadiE2xdFMODVlRhNSV1IwoU',
    appId: '1:854249361826:android:6834b028d5f532a3d022fb',
    messagingSenderId: '854249361826',
    projectId: 'evently-route',
    storageBucket: 'evently-route.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxhtayFPKkbaDCEX3Rwe9bJucpV8YRBOU',
    appId: '1:854249361826:ios:b49d2c552b084b9ad022fb',
    messagingSenderId: '854249361826',
    projectId: 'evently-route',
    storageBucket: 'evently-route.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxhtayFPKkbaDCEX3Rwe9bJucpV8YRBOU',
    appId: '1:854249361826:ios:b49d2c552b084b9ad022fb',
    messagingSenderId: '854249361826',
    projectId: 'evently-route',
    storageBucket: 'evently-route.firebasestorage.app',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsKxAZNnD7ASV0EYcek3ZsGbdsf2mgf-c',
    appId: '1:854249361826:web:1583d343fb285dcbd022fb',
    messagingSenderId: '854249361826',
    projectId: 'evently-route',
    authDomain: 'evently-route.firebaseapp.com',
    storageBucket: 'evently-route.firebasestorage.app',
    measurementId: 'G-8K7ZDJW6VS',
  );

}